### ISSUE TITLE
Updating countries and package?

### ISSUE THREAD

**Issue by mainanick** [jameslafferty/countries#3]
I would like to update the list and package by adding numeric country codes, territories, phone codes, helper functions such as (isCountry) (phone to country map function)...etc

Any contributing standard for one to adhere to?

**Comment by jameslafferty** [comment]
@mainanick I'm retooling the library right now, since it had been allowed to sit for so long. We can work on coding standards once it's in a more manageable state. I'm intending to switch over to Typescript, and fix up the testing to get rid of grunt and so forth. Once that's set up, the coding standards should be a lot clearer. Thank you so much for reminding me that it was out there and could use some attention!

**Comment by jameslafferty** [comment]
Ok @mainanick, there's still some stuff I'm working on, but I have a bunch of it fixed up. I'd welcome the help with the package. We can coordinate offline, and update the documentation here as we work through things.
